# Generated by Django 3.1.14 on 2022-02-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_messagefriendmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageFriendModel',
        ),
    ]
