# Generated by Django 3.1.14 on 2022-02-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_delete_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedmodel',
            name='file',
            field=models.FileField(default='bookfile/sh.pdf', upload_to='bookfile/'),
        ),
    ]
