# Generated by Django 3.1.13 on 2022-02-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20220215_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='star',
            field=models.PositiveIntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
