# Generated by Django 3.1.13 on 2022-02-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_comments_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='star',
            field=models.IntegerField(),
        ),
    ]
