# Generated by Django 3.1.14 on 2022-02-26 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20220219_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='star',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
