# Generated by Django 3.1.14 on 2022-03-02 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0009_auto_20220226_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmodel',
            name='sight',
            field=models.ManyToManyField(blank=True, related_name='sight', to=settings.AUTH_USER_MODEL),
        ),
    ]
