# Generated by Django 3.1.14 on 2022-03-05 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0010_feedmodel_sight'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('booklike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklike', to='books.feedmodel')),
                ('userlike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
